### ISSUE TITLE
Tells me I'm not admin when I am

### ISSUE THREAD

**Issue by Deus1855** [czsquizer/sqz_switchjob#3]
When I was getting this error I did not touch any of the files or edit anything. Fully followed install instructions,
1. Imported eh sql.sql file with no errors
2. Commented out the webhook section in the /server/main.Lua as I don't use discord
3. Nothing else was changed. I get no F8 Console Errors.

Repro Steps for Issue
 1. Use  /setjob2  ID Job JobGrade command 
 2.  Receive the bottom left notification that says I am not an admin.  
 3. I am listed as both a SuperAdmin and Admin as I am the server owner and am able to use all other admin commands/scripts. This is the only script that claims I'm not in an admin group. 
 
In order for me to use this script I had to comment out 
local allowedAdminGroups = {
    ['superadmin'] = true,
    ['admin'] = false
    -- Here you can add more groups which will be allowed to you /setjob2 command, do not forget to add comma
}

After that, I was able to use the script but what I do not want is for just anyone to go around changing people's secondary jobs as this could lead to someone assigning someone a whitelisted job.

**Comment by czsquizer** [comment]
Hello, what version of esx do you use?

**Comment by Deus1855** [comment]
ESX V1Final (1.2)

**Comment by czsquizer** [comment]
Try adding at the top, under xPlayer debug print: `print(xPlayer.getGroup())`
